const parts: {
  color: string;
  text: string;
  italic?: boolean;
  bold?: boolean;
  break?: boolean;
}[] = [
  { color: "cyan", text: "import " },
  { color: "blue2", text: "React", bold: true },
  { color: "cyan", text: ", " },
  { color: "white", text: "{ useState, useEffect, useCallback } " },
  { color: "cyan", text: "from " },
  { color: "green", text: '"react"' },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "export default ", italic: true },
  { color: "purple", text: "function " },
  { color: "blue", text: "useEasterEgg" },
  { color: "white", text: "() {" },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0const ", italic: true },
  { color: "white", text: "[input, setInput] " },
  { color: "cyan", text: "= " },
  { color: "blue", text: "useState" },
  { color: "white", text: "<" },
  { color: "teal", text: "number" },
  { color: "white", text: "[]>([])" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0const ", italic: true },
  { color: "white", text: "[active, setActive] " },
  { color: "cyan", text: "= " },
  { color: "blue", text: "useState" },
  { color: "white", text: "(" },
  { color: "orange", text: "false" },
  { color: "white", text: ")" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0const ", italic: true },
  { color: "white", text: "easterEggCode " },
  { color: "cyan", text: "= " },
  { color: "white", text: "[" },
  { color: "orange", text: "38" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "38" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "40" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "40" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "37" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "39" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "37" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "39" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "66" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "65" },
  { color: "white", text: "]" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0const ", italic: true },
  { color: "white", text: "onKeyUp " },
  { color: "cyan", text: "= " },
  { color: "white", text: "(" },
  { color: "orange", text: "e" },
  { color: "cyan", text: ": KeyboardEvent" },
  { color: "white", text: ") " },
  { color: "cyan", text: "=> " },
  { color: "white", text: "{" },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0\u00A0\u00A0const ", italic: true },
  { color: "white", text: "newInput " },
  { color: "cyan", text: "= " },
  { color: "white", text: "[" },
  { color: "cyan", text: "..." },
  { color: "white", text: "input" },
  { color: "cyan", text: ", " },
  { color: "orange", text: "e" },
  { color: "cyan", text: "." },
  { color: "teal", text: "keyCode" },
  { color: "white", text: "]" },
  { color: "cyan", text: "." },
  { color: "blue", text: "slice" },
  { color: "white", text: "(" },
  { color: "cyan", text: "-" },
  { color: "white", text: "easterEgg" },
  { color: "cyan", text: "." },
  { color: "teal", text: "length" },
  { color: "white", text: ")" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "purple", text: "\u00A0\u00A0\u00A0\u00A0if " },
  { color: "white", text: "(newInput" },
  { color: "cyan", text: "." },
  { color: "blue", text: "join" },
  { color: "white", text: "(" },
  { color: "green", text: '""' },
  { color: "white", text: ") " },
  { color: "cyan", text: "=== " },
  { color: "white", text: "easterEgg" },
  { color: "cyan", text: "." },
  { color: "blue", text: "join" },
  { color: "white", text: "(" },
  { color: "green", text: '""' },
  { color: "white", text: ")) " },
  { color: "blue", text: "setActive" },
  { color: "white", text: "(" },
  { color: "orange", text: "true" },
  { color: "white", text: ")" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "blue", text: "\u00A0\u00A0\u00A0\u00A0setInput" },
  { color: "white", text: "(newInput)" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: "\u00A0\u00A0}" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: " ", break: true },
  { color: "blue", text: "\u00A0\u00A0useEffect" },
  { color: "white", text: "(() " },
  { color: "cyan", text: "=> " },
  { color: "white", text: "{" },
  { color: "white", text: " ", break: true },
  { color: "red", text: "\u00A0\u00A0\u00A0\u00A0document" },
  { color: "cyan", text: "." },
  { color: "blue", text: "addEventListener" },
  { color: "white", text: "(" },
  { color: "green", text: '"keyup"' },
  { color: "cyan", text: ", " },
  { color: "blue", text: "onKeyUp" },
  { color: "white", text: ")" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0\u00A0\u00A0return ", italic: true },
  { color: "white", text: "() " },
  { color: "cyan", text: "=> " },
  { color: "white", text: "{" },
  { color: "white", text: " ", break: true },
  { color: "red", text: "\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0document" },
  { color: "cyan", text: "." },
  { color: "blue", text: "addEventListener" },
  { color: "white", text: "(" },
  { color: "green", text: '"keyup"' },
  { color: "cyan", text: ", " },
  { color: "blue", text: "onKeyUp" },
  { color: "white", text: ")" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: "\u00A0\u00A0\u00A0\u00A0}" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: "\u00A0\u00A0}" },
  { color: "cyan", text: ", " },
  { color: "white", text: "[" },
  { color: "blue", text: "onKeyUp" },
  { color: "white", text: "])" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: " ", break: true },
  { color: "indigo", text: "\u00A0\u00A0return ", italic: true },
  { color: "white", text: "active" },
  { color: "cyan", text: ";" },
  { color: "white", text: " ", break: true },
  { color: "white", text: "}" },
];

export default parts;
